version: '3.8'

services:
  database:
    image: postgres:latest
    env_file:
      - .dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3030:3030"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - database
    restart: always

volumes:
  postgres-data:
