name: "Build, Test, and Deploy Dockerized NestJS App (BizCRM)"

on:
  push:
    branches:
      - main
      - ci/cd-setup #temp
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432

    env:
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432
      DATABASE_NAME: ${{ secrets.POSTGRES_DB }}
      DATABASE_USER: ${{ secrets.POSTGRES_USER }}
      DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Set up Node.js
        uses: actions/setup-node@v3.1.0
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      # - name: Run Linter
      #   run: npm run lint

      - name: Start Tests
        run: npm run test